<?php
 function city_menu() {
    
    $item['admin/city'] = array(
        'title' => 'Ajax List Load',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('city'),
        'access callback' => true,
        'type' => MENU_NORMAL_ITEM,
    );
	
	$item['admin/manage_city'] = array(
        'title' => 'Manage Cities',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('manage_city'),
        'access callback' => true,
        'type' => MENU_NORMAL_ITEM,
    );
		
     return $item;
}

function main_page2() {
  return drupal_get_form('city');
  return drupal_get_form('manage_city');
}

function manage_city($form, &$form_state) {
     $form = array();
        
     $det='';
     $opt = db_select('country','n')->fields('n',array('id','country'))->execute()->fetchAll();
     $det=array();
       foreach($opt as $dett)
		{
			$det[$dett->id] = $dett->country;
		}
		
   
	
$form['city'] = array(
    '#type' => 'textfield',
    '#title' => t("Enter City name"),
	'#required' => TRUE,
  );
  
  $form['c_id'] = array(
	'#type' => 'select',
	'#title' => t("Select Country"),
	'#options' => $det,
  );
	$form['status'] = array(
		'#type' => 'select',
		'#title' => t("Status"),
		'#options' => array(t('Active'), t('Inactive')),
	);

	$form['submit'] = array(
		'#value' => 'Add City',
		'#type' => 'submit',
	);

  return $form;
}




 