<?php
 function city_menu() {
    
		/*$item['admin/city/add'] = array(
				'title' => 'Add City',
				'page callback' => 'drupal_get_form',
				'page arguments' => array('city'),
				'access callback' => true,
				'type' => MENU_NORMAL_ITEM,
		);*/

		$item['admin/city/add'] = array(
				'title' => 'Add Cities',
				'page callback' => 'drupal_get_form',
				'page arguments' => array('manage_city'),
				'access callback' => true,
				'type' => MENU_NORMAL_ITEM,
		);
	 

		$item['admin/city/edit'] = array( 
				'title' => 'Edit city', 
				'page callback' => 'drupal_get_form',
				'page arguments' => array('edit_city'),
				'access callback' => true,		
				'type' => MENU_NORMAL_ITEM,
			); 
		$item['admin/country/list'] = array(
				'title' => 'Country List',
				'page callback' => 'drupal_get_form',
				'page callback' => 'custom_table_page_display',
				'access callback' => true,
				'type' => MENU_NORMAL_ITEM,
		);

		return $item;
}

		function main_page2() {
		  return drupal_get_form('city');
		  return drupal_get_form('manage_city');
		  return drupal_get_form('edit_city');
		}

			/*function custom_table_page_display() {
			  $result = db_query('SELECT * FROM {country}');
			  $records = $result->fetchAll();
			  $content = '<pre>' . print_r($records, TRUE) . '</pre>';
			  return $content;

			}*/
function custom_table_page_display() {

	  $header = array(
			array('data' => t('id'), 'field' => 'id', 'sort' => 'ASC'),
			array('data' => t('Name')),
			array('data' => t('OPERATIONS')),
	  );

  $query = db_select('country', 'u');
  $query->fields('u', array('id','country'));  // select your required fields here
  $table_sort = $query -> extend('TableSort') // Add table sort extender.
                       -> orderByHeader($header); // Add order by headers.
					   
  $pager = $table_sort -> extend('PagerDefault')
                       -> limit(10);  // here you can limit the number of data per page.

  $result = $pager->execute();
  $rows = array();
  $a=1;  
  foreach($result as $res) {
  
    $edit = l(t('Edit'), 'admin/city/' .$res->id. '/edit');
   //$l = "edit/'.$res->id.'/edit";
   // $edit = "<a href='".$l."'>Edit</a>";
    $rows[] = array($res->id,$res->country, $edit,);
	$a++;
    $edit="";
  }
  // If rows are not empty theme and display the rows.
  $output = '';

  if (!empty($rows)) {

    $output = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'sort-table')));

    $output .= theme('pager');

  }

  else {

    $output .= t("No results found.");

  }

  return $output;

}



function manage_city($form, &$form_state) {
     $form = array();
        
     $det='';
     $opt = db_select('country','n')->fields('n',array('id','country'))-> orderBy('country', 'ASC')->execute()->fetchAll();
     $det=array();
       foreach($opt as $dett)
		{
			$det[$dett->id] = $dett->country;
		}
		
   	
$form['city'] = array(
    '#type' => 'textfield',
    '#title' => t("Enter City name"),
	'#required' => TRUE,
	
  );
  
  $form['c_id'] = array(
	'#type' => 'select',
	'#title' => t("Select Country"),
	'#options' => $det,
  );
	$form['status'] = array(
		'#type' => 'select',
		'#title' => t("Status"),
		'#options' => array(t('Active'), t('Inactive')),
	);

	$form['submit'] = array(
		'#value' => 'Add City',
		'#type' => 'submit',
	);

  return $form;
}

function edit_city($form, &$form_state) {
		$form = array();
        $edit_id = arg(3);
        $opt = db_select('country','n')->fields('n',array('id','country'))-> orderBy('country', 'ASC')->execute()->fetchAssoc();
     $det=array();
       foreach($opt as $dett)
		{
			$det[$dett->id] = $dett->country;
		}
	
     $det='';
     $opt = db_select('country','n')->fields('n',array('id','country'))-> orderBy('country', 'ASC')->execute()->fetchAll();
     $det=array();
       foreach($opt as $dett)
		{
			$det[$dett->id] = $dett->country;
		}
		
   	
$form['city'] = array(
    '#type' => 'textfield',
    '#title' => t("Enter City name"),
	'#required' => TRUE,
	//'#value' => ,
  );
  
  $form['c_id'] = array(
	'#type' => 'select',
	'#title' => t("Select Country"),
	'#options' => $det,
  );
	$form['status'] = array(
		'#type' => 'select',
		'#title' => t("Status"),
		'#options' => array(t('Active'), t('Inactive')),
	);

	$form['submit'] = array(
		'#value' => 'Add City',
		'#type' => 'submit',
	);

  return $form;
}