<?php
 
function city_menu() {
    
    $item['city'] = array(
        'title' => 'Ajax List Load',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('city'),
        'access callback' => true,
        'type' => MENU_NORMAL_ITEM,
    );
		
     return $item;
}

function main_page2() {
  return drupal_get_form('city');
}


function city($form, &$form_state) {
     $form = array();
     
     //db connection 
     $det='';
     $opt = db_select('country','n')->fields('n',array('id','country'))->execute()->fetchAll();
     $det=array();
       foreach($opt as $dett)
		{
			$det[$dett->id] = $dett->country;
		}
		

  $form['changethis'] = array(
    '#type' => 'select',
		'#title' => t("Country"),
    '#options' => $det,  
    '#ajax' => array(
      'callback' => 'select_city_callback',
      'wrapper' => 'replace_textfield_div',
      ),
  );
  
  // This entire form element will be replaced with an updated value.
 
  $form['replace_textfield'] = array(
    '#type' => 'select',
    '#title' => t("City"),
	//'#options' => $det,  
    '#prefix' => '<div id="replace_textfield_div">',
    '#suffix' => '</div>',
		'#ajax' => array(
      'callback' => 'select_city1_callback',
      'wrapper' => 'replace1_textfield_div',
      ),
  );
	
$form['replace1_textfield'] = array(
    '#type' => 'textarea',
    '#title' => t("Address"),
	  '#prefix' => '<div id="replace1_textfield_div">',
    '#suffix' => '</div>',
		  
  );
  
  return $form;
}

function select_city_callback($form, $form_state) {
  // The form has already been submitted and updated. We can return the replaced
  // item as it is.

//  $values1 =db_select('area','lb')->fields('lb',array('c_id','area'))->condition('c_id',$form_state['values']['replace_textfield'],'=')->execute()->fetchObject();
// $change_me['#value'] = $values->c_id;
// //  print_R($change_me);exit;
//  $commands = array();
//  $commands[] = ajax_command_replace("#replace_textfield_div", render($change_me));
//		 return array('#type' => 'ajax', '#commands' => $commands);


    $values =db_select('cities','c')->fields('c',array('id','city','c_id'))->condition('c_id',$form_state['values']['changethis'],'=')->execute()->fetchAll();
    //db_set_active();
    
    foreach($values as $citydetails) {
  
        $city[$citydetails->id] = $citydetails->city; 
    }
    $form['replace_textfield']['#options'] = $city;
    $form['replace_textfield']['#attributes'] = array();
    //echo "<pre>"; print_r($city); exit();
    return $form['replace_textfield'];
}

function select_city1_callback($form, &$form_state) {
		// The form has already been submitted and updated. We can return the replaced
		// item as it is.
		$values1 =db_select('area','lb')->fields('lb',array('id','area'))->condition('id',$form_state['values']['replace_textfield'],'=')->execute()->fetchObject();
		//print_R($values1);exit;
		$change_me=$form['replace1_textfield'];
		$change_me['#value'] =$values1->area;
		//print_R($change_me);exit;
		$commands = array();
		$commands[] = ajax_command_replace("#replace1_textfield_div", render($change_me));
		 return array('#type' => 'ajax', '#commands' => $commands);
}

